spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/lms-db
spring.datasource.username=49t2jbFnL9xeerB.root
spring.datasource.password=nq9S5alKASRxDd5B

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true